export const questions = [
  {
    id: '1',
    question: 'What does a red octagonal sign mean?',
    options: ['Yield', 'Stop', 'Caution', 'No Entry'],
    correctAnswer: 1,
    explanation: 'A red octagonal sign universally means "Stop". Drivers must come to a complete stop.',
    category: 'Traffic Signs',
    difficulty: 'easy',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    createdBy: '1',
    updatedBy: '1',
  },
  {
    id: '2',
    question: 'What is the maximum speed limit in residential areas?',
    options: ['25 mph', '30 mph', '35 mph', '40 mph'],
    correctAnswer: 0,
    explanation: 'In most residential areas, the speed limit is 25 mph unless otherwise posted.',
    category: 'Road Rules',
    difficulty: 'medium',
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-16'),
    createdBy: '2',
    updatedBy: '2',
  },
  {
    id: '3',
    question: 'When should you use your turn signal?',
    options: ['Only when other cars are present', 'At least 100 feet before turning', 'Only at intersections', 'Only when required by law'],
    correctAnswer: 1,
    explanation: 'You should activate your turn signal at least 100 feet before making a turn to give other drivers adequate warning.',
    category: 'Road Rules',
    difficulty: 'easy',
    createdAt: new Date('2024-01-17'),
    updatedAt: new Date('2024-01-17'),
    createdBy: '2',
    updatedBy: '2',
  },
  {
    id: '4',
    question: 'What should you do when approaching a school bus with flashing red lights?',
    options: ['Slow down and proceed carefully', 'Stop at least 20 feet away', 'Change lanes and continue', 'Honk to alert the driver'],
    correctAnswer: 1,
    explanation: 'When a school bus has flashing red lights, you must stop at least 20 feet away and wait until the lights stop flashing.',
    category: 'Road Rules',
    difficulty: 'medium',
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18'),
    createdBy: '1',
    updatedBy: '1',
  },
  {
    id: '5',
    question: 'What is the minimum following distance in good weather conditions?',
    options: ['1 second', '2 seconds', '3 seconds', '4 seconds'],
    correctAnswer: 2,
    explanation: 'The 3-second rule is the minimum safe following distance in good weather conditions.',
    category: 'Vehicle Safety',
    difficulty: 'easy',
    createdAt: new Date('2024-01-19'),
    updatedAt: new Date('2024-01-19'),
    createdBy: '1',
    updatedBy: '2',
  },
  {
    id: '6',
    question: 'What does a yellow diamond-shaped sign typically indicate?',
    options: ['Construction zone', 'Warning or caution', 'No parking', 'Speed limit'],
    correctAnswer: 1,
    explanation: 'Yellow diamond-shaped signs are warning signs that alert drivers to potential hazards or changes in road conditions.',
    category: 'Traffic Signs',
    difficulty: 'easy',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
    createdBy: '2',
    updatedBy: '2',
  },
  {
    id: '7',
    question: 'When is it legal to park in a handicap space?',
    options: ['When running a quick errand', 'Only with a valid handicap permit or license plate', 'During off-peak hours', 'Never'],
    correctAnswer: 1,
    explanation: 'Handicap parking spaces can only be used by vehicles displaying a valid handicap permit or license plate.',
    category: 'Parking',
    difficulty: 'easy',
    createdAt: new Date('2024-01-21'),
    updatedAt: new Date('2024-01-21'),
    createdBy: '1',
    updatedBy: '1',
  },
  {
    id: '8',
    question: 'What should you do if your brakes fail while driving?',
    options: ['Turn off the engine immediately', 'Pump the brakes and use the parking brake gradually', 'Swerve to avoid obstacles', 'Honk continuously'],
    correctAnswer: 1,
    explanation: 'If brakes fail, pump the brake pedal rapidly, then gradually apply the parking brake while steering to a safe area.',
    category: 'Emergency Situations',
    difficulty: 'hard',
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
    createdBy: '2',
    updatedBy: '1',
  },
];
